apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitops
spec:
  inputs:
    resources:
      - name: source
        type: git
      - name: image
        type: image
    params:
      - name: js-image
        type: string
        default: docker.io/node:12-stretch
      - name: tools-image
        type: string
        default: docker.io/csantanapr/helm-kubectl
  steps:
    - name: clone-update-repo
      image: $(inputs.params.js-image)
      workingdir: $(inputs.resources.source.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e

          # Export project name
          echo "this is my first run!"
          # echo "applicationImage: bbb" > randomtext.txt

          # clone repo
          git clone https://github.com/ibm-cloud-architecture/devops-demo-dev-env.git
          cd devops-demo-dev-env

          # update value for key applicationImage
          sed -i "/applicationImage: /c\  applicationImage: $(inputs.resources.image.url)" ./app-deploy.yaml

          # verify the value for key applicationImage got updated
          cat ./app-deploy.yaml | grep "applicationImage"

          # push changes to git
          # This email is not used and it not valid, you can ignore but git requires it
          git config --global user.email "user@example.com"
          git config --global user.name "user"

          echo $(inputs.resources.source.path)
          git add .
          git commit -m "Updated app-deploy.yaml"
          git push
