apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-release-for-artifactory-task
  namespace: kabanero
  author: Oscar I. Ricaud
  date: 04/21/20
spec:
  inputs:
    params:
      - name: asuh-image
        default: googlefu/apic_compiler:v3-amd64
        type: string
      - name: pipeline-version
        type: string
        description: This is the pipeline version we are uploading to artifactory
        default: ""
    resources:
      - name: source
        type: git
  steps:
    - name: generate-zip-file
      image: $(inputs.params.asuh-image)
      script: |

        # generate your zip file
        cd ci
        ./package.sh
      env:
        - name: PIPELINE_VERSION
          value: $(inputs.params.pipeline-version)
      resources: {}
      workingDir: $(inputs.resources.source.path)

    - name: upload-asset-to-artifactory
      image: $(inputs.params.asuh-image)
      args:
        - '-c'
        - |
          set -e
          ./scripts/upload-asset-to-artifactory.sh
      env:
        - name: PIPELINE_VERSION
          value: $(inputs.params.pipeline-version)
        - name: REPO_NAME
          value: pipeline-server
      resources: {}
      workingDir: $(inputs.resources.source.path)

    - name: update-kabanero-cr
      image: $(inputs.params.asuh-image)
      args:
        - '-c'
        - |
          set -e
          ./scripts/update-kabanero-cr.sh
      env:
        - name: REPO_NAME
          value: pipeline-server
        - name: PIPELINE_VERSION
          value: $(inputs.params.pipeline-version)
      resources: {}
      workingDir: $(inputs.resources.source.path)