apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  creationTimestamp: 2020-04-13T16:57:40Z
  generation: 2
  name: nodejs-mcm-pl
  namespace: kabanero
  ownerReferences:
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: java-microprofile
      uid: 6cc6e79b-a3cb-4a47-a3ef-7fc45d8efbd8
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: java-openliberty
      uid: 6151225d-a5c0-4dce-b852-fc858d503769
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: java-spring-boot2
      uid: b075c7c8-c794-4f0c-93aa-1cc14cdacc4a
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: nodejs
      uid: b3a420f1-edb4-41cb-9836-eea155dc511d
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: nodejs-express
      uid: 325945be-3c6b-4418-8695-7f3aa7bf8b4c
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: nodejs-loopback
      uid: 706c1bac-4455-4a65-a5d5-18d04a4eea8f
    - apiVersion: kabanero.io/v1alpha2
      controller: false
      kind: Stack
      name: or-nodejs-express-stack
      uid: 26ee83e7-af99-4573-a4e1-fffbc75e9662
  resourceVersion: "6170090"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/kabanero/pipelines/nodejs-mcm-pl
  uid: 75d9af1a-5345-44f3-a3cc-2b7a9c7f9a48
spec:
  params:
    - description: The event type
      name: event-type
      type: string
    - description: The event ref
      name: event-ref
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: test
      resources:
        inputs:
          - name: source
            resource: git-source
      taskRef:
        kind: Task
        name: igc-nodejs-test
    - name: build-push-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
        outputs:
          - name: docker-image
            resource: docker-image
          - name: git-source
            resource: git-source
      runAfter:
        - test
      taskRef:
        kind: Task
        name: nodejs-build-push-task
    - name: image-scan-task
      resources:
        inputs:
          - name: git-source
            resource: git-source
          - name: docker-image
            resource: docker-image
      runAfter:
        - build-push-task
      taskRef:
        kind: Task
        name: nodejs-image-scan-task
    - name: gitops
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      runAfter:
        - image-scan-task
      taskRef:
        kind: Task
        name: gitops-mcm-task